# Generated by Django 5.1.1 on 2024-09-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
        migrations.AddField(
            model_name='room',
            name='catagory',
            field=models.CharField(choices=[('Home', 'Home'), ('Apartment', 'Apartment'), ('ROOMS', 'Rooms'), ('Office', 'Office'), ('Farmhouse', 'Farmhouse')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
