# Generated by Django 5.1.1 on 2024-09-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_room_images_room_catagory_alter_room_baths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='phone',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
