# Generated by Django 5.1.1 on 2024-09-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='location',
            new_name='city',
        ),
    ]
