# Generated by Django 5.1.1 on 2024-10-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='catagory',
            field=models.CharField(choices=[('Home', 'Home'), ('Apartment', 'Apartment'), ('ROOMS', 'ROOMS'), ('Office', 'Office'), ('Farmhouse', 'Farmhouse')], max_length=255, null=True),
        ),
    ]
