# Generated by Django 5.1.1 on 2024-10-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_room_area_alter_room_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Area',
        ),
    ]
