# Generated by Django 5.1.1 on 2024-10-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_room_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
    ]
