# Generated by Django 5.1.1 on 2024-10-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_room_owner_alter_room_price_alter_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(null=True),
        ),
    ]
