# Generated by Django 5.1.1 on 2024-10-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_room_baths_alter_room_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.CharField(default='Lahore', max_length=255),
            preserve_default=False,
        ),
    ]
